# Generated by Django 4.1.4 on 2022-12-17 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0003_experience_category"),
        ("rooms", "0003_room_category"),
        ("medias", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Media",
            new_name="Photo",
        ),
    ]
