# Generated by Django 4.1.4 on 2022-12-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0003_experience_category"),
        ("rooms", "0003_room_category"),
        ("wishlists", "0002_alter_wishlist_experiences_alter_wishlist_rooms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="experiences",
            field=models.ManyToManyField(blank=True, to="experiences.experience"),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="rooms",
            field=models.ManyToManyField(blank=True, to="rooms.room"),
        ),
    ]
