# Generated by Django 4.1.4 on 2022-12-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0002_rename_price_house_price_per_night"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="pet_allowed",
            field=models.BooleanField(default=True),
        ),
    ]
